
Max Decision Length:  8687
Traceback (most recent call last):
  File "/home2/adyansh/LLM4ADR/Approach/Code/training.py", line 87, in <module>
    tokenized_train = preprocess_function(train)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/adyansh/LLM4ADR/Approach/Code/training.py", line 78, in preprocess_function
    inputs = data["Context"].apply(lambda x: perform_rag(x, 5))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/adyansh/LLM4ADR/research/lib/python3.11/site-packages/pandas/core/series.py", line 4924, in apply
    ).apply()
      ^^^^^^^
  File "/home2/adyansh/LLM4ADR/research/lib/python3.11/site-packages/pandas/core/apply.py", line 1427, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home2/adyansh/LLM4ADR/research/lib/python3.11/site-packages/pandas/core/apply.py", line 1507, in apply_standard
    mapped = obj._map_values(
             ^^^^^^^^^^^^^^^^
  File "/home2/adyansh/LLM4ADR/research/lib/python3.11/site-packages/pandas/core/base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home2/adyansh/LLM4ADR/research/lib/python3.11/site-packages/pandas/core/algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "/home2/adyansh/LLM4ADR/Approach/Code/training.py", line 78, in <lambda>
    inputs = data["Context"].apply(lambda x: perform_rag(x, 5))
                                             ^^^^^^^^^^^^^^^^^
  File "/home2/adyansh/LLM4ADR/Approach/Code/training.py", line 70, in perform_rag
    context += result.page_content + "\n## Decision\n" + result.metadata['Decision'] + "\n\n"
    ^^^^^^^
UnboundLocalError: cannot access local variable 'context' where it is not associated with a value